name: deploy
on:
  workflow_run: # Pylint, Pytest 작업이 완료 된 후 실행
    workflows: ["Pylint", "Pytest"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: remote-ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd cicd
          git pull